### ISSUE TITLE
Match Union of two schemas

### ISSUE THREAD

**Issue by Greedquest** [asottile/cfgv#73]
Sorry if this is not the correct place to ask, this may be a feature request or just a question...

I have:
```python
REFERENCE_SCHEMA = cfgv.Map(
    "Reference", "src",
    cfgv.Required("src", cfgv.check_string), #path to file on system
    cfgv.NoAdditionalKeys("src")
)

REFERENCE_ALT = cfgv.Map(
    "Reference", "name",
    cfgv.Required("name", cfgv.check_string),
    cfgv.OptionalNoDefault("major", cfgv.check_int), 
    cfgv.ConditionalOptional("minor", cfgv.check_int, 0,  "major", cfgv.Not(cfgv.MISSING), ensure_absent=True),  # side-note; this doesn't work
)

COMPLETE_SCHEMA = cfgv.Map(
    "Config.toml",
    None,
    cfgv.OptionalRecurse(
        key="references", schema=cfgv.Array(REFERENCE_ALT), default=[],
    ),
)
```

Which is meant to mean either of these two options is permitted in my config.toml:

```toml
[[references]]
src = 'C:\WINDOWS\system32\scrrun.dll'

[[references]]
name = "Microsoft XML"
major = 3 # optional
minor = 0 # optional only if major provided, otherwise forbidden
```
I'm not sure how to do a Union of those two schemas?
